
`r chapnum = 9`

# Premium Foundations {#ChapPremiumFoundations}

*Chapter Preview.* Setting prices for insurance products, i.e., premiums, is an important task for actuaries and other data analysts. This chapter introduces the foundations for pricing non-life products.

## Introduction to Ratemaking {#S:IntroductionRatemaking}

***
In this section, you learn how to:

- Develop pure premiums
- Develop a technical price to includes pure premiums, expenses and profits
- Calculate an indicated rate change
- Summarize a strategy for extending pricing to include heterogeneous risks and trends over time

***

This chapter explains how you can determine the appropriate price for an insurance product. As described in Section \@ref(S:PredModApps), one of the core actuarial functions is `r Gloss('ratemaking')`, where the analyst seeks to determine the right price for a risk.

A `r Gloss('price')` is the consideration exchanged for a good or service. In insurance, we refer to this consideration as the `r Gloss('premium')` and the service provided by the insurer is protection against contingent events. The amount of protection varies by risk being insured. For example, in homeowners insurance, the amount of insurance protection depends on the home value. In life insurance, the amount of protection may depend on a policyholder's financial status (e.g., income and wealth) and their perceived need for financial security. So, it is common to express insurance prices as a unit of the protection being purchased, for example, a price per thousand dollars of coverage on a home or benefit in the event of death. These prices/premiums are known as `r Gloss('rates')` because they are expressed in standardized units.

Unlike other products, the costs of insurance protection are not known at the sale of the contract. If the `r Gloss('insured contingent event')`, such as the loss of a house or life, does not occur, then the contract costs are only administrative (e.g., to set up the contract) and are relatively minor. If an insured event occurs, then the cost includes not only administrative costs but also claim payment(s) and expenses to settle claims. So, the cost is random when the contract is written, and protection from that randomness is the basis of insurance. 

Because costs are unknown at the time of sale, insurance pricing differs from common economic approaches. This chapter introduces traditional actuarial approaches to determine prices as a function of insurance costs. As we will see, this pricing approach is sufficient for some insurance markets, such as personal automobile or homeowners, where the insurer has a portfolio of many independent risks. However, there are other insurance markets where actuarial prices only provide an input to general market prices. To reinforce this distinction, actuarial cost-based premiums are sometimes known as `r Gloss('technical prices')`. 

To develop technical prices, it is helpful to think of a premium as revenue source that provides for claim payments, contract expenses, and an required return for the capital provider. We formalize this relationship as follows:

$$
\begin{equation}
\small{
\text{Premium} = \dfrac{\text{Pure Premiums} + \text{Fixed Expenses} }{1 - \text{Variable Expense Rate} - \text{Profit}}
\\
\text{where:}\\
\text{Pure Premiums} = \dfrac{\text{Estimated Claims and Claims Adjustment Expense}}{\text{Exposures}}\\
\text{or:}\\
\text{Pure Premiums} = \dfrac{\text{Estimated Claim Counts}}{\text{Exposures}} \times \dfrac{\text{Estimated Claims and Claims Adjustment Expense}}{\text{Estimated Claim Counts}}\\
}(\#eq:PremiumEquation)
\end{equation}
$$

`Non-claim Expenses` include insurer costs that vary by premium (such as sales commissions), and those that do not (such as building costs and employee salaries). We include those costs through the Fixed Expenses and Variable Expense Rate of the @ref(#eq:PremiumEquation).

An insurer requires capital to support operations. The capital provider will reasonably expect to earn a profit from insuring risk. 

### Chapter Orginization

This presentation of this section follows the premium equation.

* In Section \@ref(#S:DataSources), we first present the sources of information that support premium devleopment. 
* We discuss this development of the pure premiums in Section \@ref(#S:claims).
* In Section \@ref(S:expenses), we discuss fixed and variable non-claim expenses.
* In Section \@ref(S:profit), we discuss the provision for profit.

There will also be cases, such as a single contract issued to a large corporation to insure all of its buildings against fire damage, where the use of only an expectation for pricing is insufficient. So, Section \@ref(S:PricingPrinciples) also summarizes alternative premium principles that incorporate uncertainty into our pricing. Note that an emphasis of this text is estimation of the entire distribution of losses so the analyst is not restricted to working only with expectations.

## Data Sources {#S:DataSources}
As we have seen in Section \@ref(S:AggRateMaking), insurers consider aggregate information for ratemaking such as exposures to risk, premiums, expenses, claims, and payments. This aggregate information is also useful for managing an insurer’s activities; financial reports are commonly created at least annually and often quarterly. At any given financial reporting date, information about recent policies and claims will be ongoing and necessarily incomplete; this section introduces concepts for projecting risk information so that it is useful for ratemaking purposes.

Insurers generally store information about insured risks, such as exposures, premiums, claim counts, losses, and rating factors, into three databases:

* *policy database* - contains information about the risk being insured, the policyholder, and the contract provisions
* *claims database* - contains information about each claim; these are linked to the policy database.
* *payment database* - contains information on each claims transaction, typically payments but may also changes to *case reserves*. These are linked to the claims database.

Insurers will aggregate the information in these detailed databases to develop the information needed for financial reports. As described in this chapter, insurers’ actuaries will also use this information to develop the premiums.

In developing premiums and rates, its important that we use claims information and exposure information that is comparable. Most ratemaking uses an accident year approach. In this approach, we relate claims incurred during a specified period to the premium or exposure "earned" during that same period, without consideration of the period in which the underlying policy was written. For example a 12 month policy issued on 1 July 2019, may result in events that produce claims in 2019 or 2020, and the claims are assigned to the year of the event. Generally, we earn premiums and exposures on a pro-rata as to time basis as presented in the following table:

[Table 9.7] gives detailed illustrative calculations for a portfolio of four illustrative policies.

<a id=tab:9.7></a>

[Table 9.7]: \#tab:9.7

Table 9.7. **Exposures for Four 12-Month Policies**

$$
\small{
\begin{matrix}
\begin{array}{cl|cc|cc|cc|c}
  \hline
&  & & & & & &&\text{In-Force} \\
&\text{Effective} & \text{Written}& \text{Exposure} & \text{Earned} &\text{Exposure}& \text{Unearned} &\text{Exposure}&  \text{Exposure} \\
{Policy} &\text{Date}         & 2019 & 2020 & 2019 & 2020 & 1/1/2019 & 1/1/2020 & 1/1/2020 \\   \hline
\text{A}&\text{1 Jan 2019}   & 1.00 & 0.00 & 1.00 & 0.00& 0.00 & 0.00 & 0.00 \\
\text{B}&\text{1 April 2019} & 1.00 & 0.00 & 0.75 & 0.25 & 0.25 & 0.00& 1.00 \\
\text{C}&\text{1 July 2019}  & 1.00 & 0.00 & 0.50 & 0.50 & 0.50 & 0.00& 1.00 \\
\text{D}&\text{1 Oct 2019}   & 1.00 & 0.00 & 0.25 & 0.75 & 0.75 & 0.00& 1.00 \\ \hline
 &  Total       & 4.00 & 0.00 & 2.50 & 1.50 & 1.50 & 0.00 & 3.00 \\
  \hline
  \hline
\end{array}
\end{matrix}
}
$$


## Pure Premiums {#S:claims}

The `Claims and Claim Adjustment Expenses` in equation \@ref(eq:PremiumEquation) are random, and so, as a baseline, we use the *expected costs* to determine rates. To develop our initial understanding, we will consider the insurer that enters into many contracts with risks that are similar except, by pure chance, in some cases the insured event occurs, and in others, it does not. The insurer is obligated to pay the total amount of claim payments for all contracts. If the risks are similar, then all policyholders are equally likely to contribute to the total loss. So, from this perspective, it makes sense to consider average claim payment over many insureds. From probability theory, specifically the law of large numbers, we know that the average of `r Gloss('iid')` risks is close to the expected amount, so we use the expectation as a baseline pricing principle. 

In this chapter, we present the development of average premium levels for a portfolio of homogeneous risks. In chapter \@ref(#ChapRiskClass), we present approaches to develop classification plans which adjust those average premiums to recognize various risk characteristics. In chapter \@ref(#ChapBonusMalus), we present approaches to develop premiums that consider the claim experience of an individual insured. 

The terms `r Gloss('loss')` and `r Gloss('claim')` refer to the amount of compensation paid or payable to the claimant under the terms of the insurance policy. Definitions can vary:
* Sometimes, *claim* is used interchangeably with the term *loss*.
* In some insurance and actuarial sources, *loss* is the amount of damage sustained in an insured event. The *claim* is the amount paid by the insurer. Differences between *loss* and *claim* amounts are typically due to the coverage terms such as deductibles and policy limits.
* In economics, a *claim* is a demand for payment by an insured or by an injured third party under the terms and conditions of the insurance contract, and the *loss* is the amount paid by the insurer.

This text will follow the second bullet.

Also, there are two categories of claim adjustment expenses. 
* Allocated claim adjustment expenses can be attributed to a specific claim, and are generally comprised of investigation expenses legal expenses to defend or settle the claim. 
* Unallocated claim adjustment expenses can not be assigned to individual claims (e.g., claim adjuster salaries.) Actuaries often review claims and allocated claim adjustment expenses in aggregate as the latter is often a function of the former. 

Claims and allocated claim adjustment expenses are sometimes inversely correlated as additional defend expenses may result in lower claim payments. In this section, references to claims also include allocated claims adjustment expenses. In this chapter we are focused on the claims and allocated claims adjustment expenses per unit exposure. That rate is referred to as a pure premium.

Insurers will include a provision for unallocated claims adjustment expenses either as a percentage of claims and allocated claims expenses or premiums. We discuss unallocated claims adjustment expenses separately in this section.

To develop the pure premiums, actuaries will typically review claims experience over a multi-year (typically three to seven years) period. The use of a multi-year period smooths the year-to-year randomness. The expected pure premium is generally A weighted average of the observations in the experience period. The weights generally balance responsiveness to more recent experience and the stability of a longer-term period. To support the understanding of the presentation of the development of pure premiums, we provide the following pure premium equation:

$$ \text{Pure Premium}^{(t)} = \sum_{i=1}^n w_i \dfrac{\text{Claims and Claims Expenses}_{i}^{(t)}}{\text{Exposure}_i^{(t)}}$$
Where we can develop projected claims and claims expenses based on ultimate claims and allocated claims adjustment expenses from our experience period:

$$ \text{Claims and Claims Expenses}_{i}^{(t)} =  C_i^{\text{x}LL, \text{x}Cat} \times T_{i}^{(t)} \times LL \times CP \times UE$$
Or, we can estimate projected claims and claims expenses as the product of projected claim frequency and claims severity:

$$ \text{Claims and Claims Expenses}_{i}^{(t)} =  E[X] \times \times E[N] \times UE$$
Under the latter approach, we assume the projected frequency and severity already include the various adjustments described below.

$$ \text{Exposure}_{i}^{(t)} =  \text{Exposure}_i\times E_{i}^{(t)}$$

where:
* $C_i^{\text{x}LL, \text{x}Cat}$ is historical claims experience for year $i$, excluding large losses and catastrophes
* $T_i$ is a claim trend factor to adjust year $i$ to the cost level of year $t$
* $ET_i$ is a exposure trend factor to adjust year $i$ to the cost level of year $t$
* $LL$ is large loss factor
* $CP$ is a catastrophe provision
* $UE$ is the unallocted claims adjustment expense factor
* $E[X]$ is the projected average severity per claim
* $E[N]$ is the projected number of claims
* $w_i$ is the weight for year $i$ in an $n$ year experience period.


<!-- I suggest deleting the following section, it's really more about the development of ultimate losses, i.e., loss reserving and I don't see value in repeating it here (and there is a risk that the discussion conflicts with the loss reserving chapter) -->

<!-- To establish additional terminology, it is helpful to follow the timeline of a claim as it develops. In Figure \@ref(fig:ClaimDevelopment), the claim occurs at time $t_1$, and the insuring company is notified at time $t_3$. There can be a gap between occurrence and notification such that the end of a company financial reporting period, known as a `r Gloss('accounting date')`, occurs ($t_2$) before the loss is reported. In this case, the claim is said to be `r Gloss('incurred but not reported')` at this valuation date. -->

<!-- Until the claim is settled, the reported claim is considered an `r Gloss('open claim')`. After claim notification, there may be one or more loss payments. Not all payments may be made by the next valuation date ($t_4$). -->

<!-- As the claim develops, eventually, the company deems its financial obligations on the claim to be resolved and declares the claim `r Gloss('closed')`. However, it is possible that new facts arise, and the claim must be re-opened, giving rise to additional loss payments prior to being closed again. -->

<!-- (ref:ClaimDevelopment) **Timeline of Claim Development** -->

<!-- ```{r ClaimDevelopment, fig.cap='(ref:ClaimDevelopment)', out.width='75%',  fig.asp=0.5, fig.align='center', echo=FALSE} -->
<!-- plot.new() -->
<!-- par(mar=c(0,0,0,0), cex=1.1) -->
<!-- plot.window(xlim=c(0,20),ylim=c(0,10)) -->

<!-- arrows(1,1,19.8,1,code=2,lwd=2,angle=25,length=0.10) -->
<!-- text(0,2,labels="Occurrence",adj=0, cex=0.8) -->

<!-- text(3,4,labels="Valuation\nDate 1",adj=0, cex=0.8) -->
<!-- text(4,2,labels="Notification",adj=0, cex=0.8) -->
<!-- text(6,8,labels="Loss Payments",adj=0, cex=0.8) -->
<!-- text(9,4,labels="Valuation\nDate 2",adj=0, cex=0.8) -->
<!-- text(11,8,labels="Loss\nPayments",adj=0, cex=0.8) -->
<!-- text(13,2,labels="Closure",adj=0, cex=0.8) -->
<!-- text(14.5,4,labels="Re-\nOpening",adj=0, cex=0.8) -->
<!-- text(16,8,labels="Loss\nPayments",adj=0, cex=0.8) -->
<!-- text(18,4,labels="Closure",adj=0, cex=0.8) -->

<!-- arrows(3.8,3.3,3.8,1.2,code=2,lwd=2,angle=25,length=0.10) -->
<!-- arrows(9.8,3.3,9.8,1.2,code=2,lwd=2,angle=25,length=0.10) -->
<!-- arrows(15.3,3.3,15.3,1.2,code=2,lwd=2,angle=25,length=0.10) -->
<!-- arrows(18.8,3.3,18.8,1.2,code=2,lwd=2,angle=25,length=0.10) -->

<!-- arrows(6.8,7.7,6.8,1.2,code=2,lwd=2,angle=25,length=0.10) -->
<!-- arrows(7.1,7.7,7.1,1.2,code=2,lwd=2,angle=25,length=0.10) -->
<!-- arrows(7.9,7.7,7.9,1.2,code=2,lwd=2,angle=25,length=0.10) -->

<!-- arrows(11.4,7.2,11.4,1.2,code=2,lwd=2,angle=25,length=0.10) -->
<!-- arrows(12,7.2,12,1.2,code=2,lwd=2,angle=25,length=0.10) -->

<!-- arrows(16.6,7.2,16.6,1.2,code=2,lwd=2,angle=25,length=0.10) -->
<!-- arrows(17,7.2,17,1.2,code=2,lwd=2,angle=25,length=0.10) -->

<!-- text(1,1,labels="X",adj=0, cex=0.8) -->
<!-- text(4.8,1,labels="X",adj=0, cex=0.8) -->
<!-- text(13.8,1,labels="X",adj=0, cex=0.8) -->

<!-- text(1,0.3,expression(t[1]),adj=0, cex=0.8) -->
<!-- text(3.8,0.3,expression(t[2]),adj=0, cex=0.8) -->
<!-- text(4.8,0.3,expression(t[3]),adj=0, cex=0.8) -->
<!-- text(9.8,0.3,expression(t[4]),adj=0, cex=0.8) -->
<!-- ``` -->

<!-- - `r Gloss('Accident date')` - the date of the occurrence which gave rise to the claim. This is also known as the *date of loss* or the *occurrence date*. -->
<!-- - `r Gloss('Report date')` - the date the insurer  receives notice of the claim. Claims not currently known by the insurer are referred to as unreported claims or *incurred but not reported (IBNR) claims*. -->

Recall that a claim is the amount paid or payable to claimants under the terms of insurance policies. Further, we have:
- *Paid claims* are those losses for a particular period that have actually been paid to claimants.
- Where there is an expectation that payment will be made in the future, a claim will have an associated *case reserve* representing the estimated amount of that payment. Case adjusters establish case reserves separately for each open claim based on the information available.
- *Reported claims*, also known as *case incurred claims* or *incurred claims*, is the sum of paid claims and case reserves

The *ultimate claim* is the amount required to close and settle all claims for a defined group of policies. From our pure premium equation, we note that there are two approaches to development of the claims and claims expemse provision. We can either use estimates of ultimate claims and claims adjustment expenses which can as developed as desribed in Section \@ref(#ChapLossReserves) or we can use projections of frequency and severity separately as described Section \@ref(#ChapFrequency) and Section \@ref(#ChapSeverity), respectively. In this section, we present the use of use of those ultimate claims in developing pure premiums, or the rate of claims per unit exposure.


### Adjustments to Claims and Allocated Claims Adjustment Expenses

In this section we review adjustments to historical ultimate claims that are required to support development of prospective rates. These adjustments include trending large loss adjustments and provisions for catastrophes. Finally, we discuss approaches to incorporate unallocated claims adjustment expense.

#### Trending {#s:Trending}
However, each of the years of the experience period has a different underlying cost level and our goal is to estimate claims at the cost level of the prospective policy period. Consider, for example, if costs were rising at a rate of 5% per annum. All else equal, the estimated ultimate cost for time $t + 2$ would be $1.05^2$ times the costs of claims from time $t$. Trending is the process of adjusting ultimate losses from historical to prospective cost levels. 

Actuaries will often consider separate trends for the frequency of claims and the severity of claims. Also actuaries often state past trends separately from future trends. Past trends reflect changes that have taken place between the experience period of the rate calculation and the valuation date. Future trends reflect expectations of change between the valuation date and the prospective policy period.

There are various approaches to estimating severity trend rates. Two common approaches include the estimation of trend rates based on external cost indices and the estimation of trend rates based on claims experience.  The former approach generally uses government data such as the consumer price index, or components thereof. In the latter approach actuaries will often fit regression models to discern the rate of change in average claims values over time. 

Due to the lack of external indices that would be appropriate as a basis for claims frequency models, actuaries generally either estimate frequency trend based on company experience or assume that frequency trend is 0%.

It's also common to review pure premium trends directly. Although the pure premium trend is effectively a combination of the frequency and severity trends, analysis of pure premiums may mask underlying changes in frequency and severity when they are inversely correlated.

### Large Loss and Catastophe Provisions

Consider, for example, if an insurer were considering a five-year experience period and that experience period included a one-in-10-year event. If we did not adjust that data, we would effectively be overestimating claim amounts for that category of claims.

In ratemaking we remove these unusual large losses and catastrophe losses from the experience period data, and then add a provision consistent with the longer term average cost of large losses or catastrophes. Although large loss adjustments are commonly based on the insurer’s claims experience, the provision for catastrophes is often based on catastrophe models developed by specialists. Adjustments for catastrophes are more common in property insurance while adjustments for large losses are more common in liability insurance.

### Unallocated Claims Adjustment Expenses

Some insurers include unallocated claims adjustment expenses as a percentage of claims and allocated claims adjustment expenses, while other insurers include unallocated claims adjustment expenses as a percentage of premiums. In our discussion we use the the former approach. For insurers that use the latter approach, the inclusion of a provision for unallocated claims adjustment expenses would follow that described below for other non-claim expenses. Generally, insurers estimate $UE$ by reviewing historical ratios of those payments to claims and allocated claims adjustment expense payments. 

## Expsoures {#S:ExposureToRisk}

The denominator of the pure premium equation is "`r Gloss('exposure', '7.2, 7.4')`." We use exposures to standardize heterogeneous risks. To explain exposures, let us use *scale distributions* that we learned about in Chapter \@ref(ChapSeverity). To recall a `r Gloss('scale distribution', '7.4')`, suppose that $X$ has a `r Gloss('parametric distribution')` and define a rescaled version $R = X/E$, $E > 0$. If $R$ is in the same parametric family as $X$, then the distribution is said to be a scale distribution. As we have seen, the gamma, exponential, and Pareto distributions are examples of scale distributions.

Intuitively, the idea behind exposures is to make risks more comparable to one another. For example, it may be that risks $X_1, \ldots, X_n$ are from different distributions and yet, with the choice of the right exposures, the rates $R_1, \ldots, R_n$ are from the same distribution. Here, we interpret the rate $R_i = C_i/E_i$ to be the loss divided by exposure.

[Table 9.3] provides a few examples. We remark that this table refers to "earned" car and house years, concepts that are be explained in Section \@ref(S:DataSources).

<a id=tab:9.3></a> 

[Table 9.3]: \#tab:9.3

Table 9.3. **Commonly used Exposures in Different Types of Insurance**

$$
\small{
\begin{matrix}
\begin{array}{ll}
\text{Type of Insurance} & \text{Exposure Basis} \\\hline
\text{Personal Automobile} &  \text{Earned Car Year, Amount of Insurance Coverage} \\
\text{Homeowners} &  \text{Earned House Year, Amount of Insurance Coverage}\\
\text{Workers Compensation}  & \text{Payroll}\\
\text{Commercial General Liability} &  \text{Sales Revenue, Payroll, Square Footage, Number of Units}\\
\text{Commercial Business Property}  & \text{Amount of Insurance Coverage}\\
\text{Physician's Professional Liability}  & \text{Number of Physician Years}\\
\text{Professional Liability}  & \text{Number of Professionals (e.g., Lawyers or Accountants)}\\
\text{Personal Articles Floater} &  \text{Value of Item} \\
  \hline
\end{array}
\end{matrix}
}
$$


#### Criteria for Choosing an Exposure  {-}

An exposure base should meet the following criteria. It should:

- be an accurate measure of the quantitative exposure to loss
- be easy for the insurer to determine (at the time the policy is initiated) and not subject to manipulation by the insured,
- be easy to understand by the insured and to calculate by the insurer,
- consider any preexisting exposure base established within the industry.

To illustrate, consider personal automobile coverage. Instead of the exposure basis "earned car year," a more accurate measure of the quantitative exposure to loss might be number of miles driven. Historically, this measure had been difficult to determine at the time the policy is issued and subject to potential manipulation by the insured and so it is still not typically used. Modern telematic devices that allow for accurate mileage recording is changing the use of this variable in some marketplaces.

As another example, the exposure measure in `r Gloss('commercial business property')`, e.g. fire insurance, is typically the amount of insurance coverage. As property values grow with inflation, so will the amount of insurance coverage. Thus, rates quoted on a per amount of insurance coverage are less sensitive to inflation than otherwise.


## Other Provisions in the Premium

### Non Claim Expenses

Non-claim insurer Operating expense costs include commissions, premium taxes, and other expenses such as salaries, rent, and inspections. 
* Some expenses (such as commissions and premium taxes) vary with premiums are "variable" or "premium variable expenses."
* Other expenses (such as general administrative and head office costs) are not proportional to premium.

For these expenses, insurers will typically relay of either historical expense ratios, budgeted amounts, or financial forecasts.

We include fixed expenses in our premium equation on a per exposure basis and we include variable expenses as a rate per unit premium. 

## Investment Income and Profit

An insurer requires capital to support operations.  The insured pays a premium for the promise of the insurer to pay a claim in the future. Capital serves as protection for the policyholder in the event that premiums are insufficient to pay claims. 

The capital provider will reasonably expect to earn a profit from insuring risk. Generally, the required profit is expressed a return on equity. A portion of required profit is earned from investment income from two sources: policyholder cashflows and investment of the insurer's surplus. To the extent that investment income is insufficient to provide the required rate of return, the premiums will also need to include an `r Gloss('underwriting profit')` provision. 

We generally express the total required rate of return as an after-tax return on equity. 

The premium equation above is slightly simplified to promote the understanding of the claims and expense provisions in Section \@ref(#S:claims) and exposures in Section \@ref(S:expenses).We now refine the equation to consider investment income.We now consider the other source on an insurer's profit, investment income. We first consider policyholder cashflows, i.e., premiums, claims and claim adjustment expenses and non-claim expenses. We consideration of investment income on policyholder by discounting each of the the cashflows of each of these components of the premium equation.

* There may be a delay in the insurer's receipt of premium, perhaps because the insurer offers its incured payment plans.
* Claims and claims adjustment expenses are paid over a period that extends beyond the policy term. Generally, property coverages have the shortest payment stream, with all claims being settled and paid over a period that extends between 2 and 5 years, depending on the complexity of the determination of damages. Litigated liability covearges will have intermediate payment streams that range from three to 10 years. Finally, coverages such as workers compensation, offer lifetime benefits that extend forty years or longer. 
* Non-claim expense are largely paid over the term of the policy period.

We can rewrite our premium equation to capture the discounting. We replace the unity in denominator with a premium delay factor and we recognize the discounting of claims and claims adjustments expenses (in the pure premium) and non-claim expenses. 

$$
\begin{equation}
\small{
\text{Premium} = \dfrac{\text{Discounted Pure Premiums} + \text{Discounted Fixed Expenses}} {\text{Premium Delay} - \text{Variable Expense Rate} - \text{Profit}}\\
}(\#eq:dPremiumEquation)
\end{equation}
$$

We recognize that the discounting effect of the numerator is significantly greater than the effect in the denominator. As a result, consideration of investment income on policyholder cash flows serves to reduce the premium. If the profit provision in the premium equation were 0, the the premium would equal the present value of the cash flows of the insurance policy. 

However, as we discussed the insurer will also require a return on its capital. Generally, coverages that are riskier, i.e., have more variability, will require more capital. Every claim submitted to the insurer has access to all of the capital of the insurer. In insurance, capital is often referred to as surplus. For ratemaking, we notionally allocate capital to coverage using premium to surplus ratios and we state the required rate of return on an after-tax basis. We have to convert that return to percent of premium to include in our premium equation. For example, if we assume a 2:1 premium:surplus ratio, a required after-tax rate of return of 12% and a tax rate of 30%, then the profit provision in the premium would be:

$$
\begin{equation}

\dfrac{12~\text{after tax return}}{\text{surplus}} \times \dfrac{1 \times \text{surplus}}{2 \times \text{premium}} \times \dfrac{1~\text{pre-tax}}{0.7~\text{after tax}} = \dfrac{8.6~\text{pre-tax return}}{\text{premium}}

\end{equation} 
$$

## Pricing Principles {#S:PricingPrinciples}

***
In this section, you learn how to:

- Describe common actuarial pricing principles
- Describe properties of pricing principles
- Choose a pricing principle based on a desired property

***


Approaches to pricing vary by the type of contract. For example, personal automobile is a widely available product throughout the world and is known as part of the *retail general insurance* market in the United Kingdom. Here, one can expect to do pricing based on a large pool of independent contracts, a situation in which expectations of losses provide an excellent starting point. In contrast, an actuary may wish to price an insurance contract issued to a large employer that covers complex health benefits for thousands of employees. In this example, knowledge of the entire distribution of potential losses, not just the expected value, is critical for starting the pricing negotiations. To cover a range of potential applications, this section describes general premium principles and their properties that one can use to decide whether or not a specific principle is applicable in a given situation.


### Premium Principles

The prior sections of this chapter introduce traditional actuarial pricing principles that provide a price based only target rates of return and the cost to insure the risk; the price does not depend on the demand for insurance. 

Assume that the loss $X$ has distribution function $F(\cdot)$ and that there exists some rule (which in mathematics is known as a *functional*), say $H$, that takes $F(\cdot)$ into the positive real line, denoted as $P = H(F)$. For notation purposes, it is often convenient to substitute the random variable $X$ for its distribution function and write $P = H(X)$. [Table 9.1] provides several examples. 

[Table 9.1]:\#tab:9.1

<a id=tab:9.1></a>

Table 9.1. **Common Premium Principles**

$$
\small{
\begin{array}{ll}
\text{Description } & \text{Definition } (H(X)) \\\hline
\text{Net (pure) premium} &  {\rm E}[X] \\
\text{Expected value} & (1+\alpha){\rm E}[X]\\
\text{Standard deviation}  & {\rm E}[X]+\alpha ~SD(X)\\
\text{Variance} & {\rm E}[X]+\alpha ~{\rm Var}(X)\\
\text{Zero utility}  & \text{solution of }u(w) = {\rm E} [u(w + P - X)]\\
\text{Exponential}  & \frac{1}{\alpha} \log {\rm E} [e^{\alpha X}]\\
\hline
\end{array}
}
$$
  
  
  
A premium principle is similar to a `r Gloss('risk measure')` that is introduced in Section \@ref(S:RiskMeasure). Mathematically, both are rules that map the loss `r Gloss('rv')` of interest to a numerical value. From a practical viewpoint, a premium principle provides a guide as to how much an insurer will charge for accepting a risk $X$. In contrast, a risk measure quantifies the level of uncertainty, or riskiness, that an insurer can use to decide on a capital level to be assured of remaining solvent.

NOTE TO BRIAN: This is the original paragraph
The net, or pure, premium essentially assumes no uncertainty. The expected value, standard deviation, and variance principles each add an explicit loading for uncertainty through the risk parameter $\alpha \ge 0$. For the principle of zero utility, we think of an insurer with utility function $u(\cdot)$ and wealth *w* as being indifferent to accepting and not accepting risk $X$. In this case, $P$ is known as an indifference price or, in economics, a reservation price. With exponential utility, the principle of zero utility reduces to the exponential premium principle, that is, assuming $u(x) = (1-e^{-\alpha x})/\alpha$.

For small values of the risk parameters, the variance principle is approximately equal to exponential premium principle, as illustrated in the following special case.

***

**Special Case: Gamma Distribution**. Consider a loss that is gamma distributed with parameters $\eta$ and $\theta$ (we usually use $\alpha$ for the location parameter but, to distinguish it from the risk parameter, for this example we call it $\eta$). From the Appendix Chapter \@ref(ChapSummaryDistributions), the mean is $\eta~ \theta$ and the variance is $\eta ~\theta^2$. Using $\alpha_{Var}$ for the risk parameter, the variance premium is  $H_{Var}(X) = \eta~ \theta+\alpha_{Var} ~(\eta ~\theta^2)$. From this appendix, it is straightforward to derive the well-known moment generating function, $M(t) = {\rm E} [e^{tX}] = (1-t\theta)^{-\eta}$. With this and a risk parameter $\alpha_{Exp}$, we may express the exponential premium as 

$$
H_{Exp}(X) = \frac{-\eta}{\alpha_{Exp}} \log\left(1-\alpha_{Exp} \theta\right).
$$
To see the relationship between $H_{Exp}(X)$ and $H_{Var}(X)$, we choose $\alpha_{Exp} = 2 \alpha_{Var}$. With an approximation from calculus ($\log(1-x) = -x - x^2/2 - x^3/3 - \cdots$), we write

$$
\begin{array}{ll}
H_{Exp}(X) &= \frac{-\eta}{\alpha_{Exp}} \log\left(1-\alpha_{Exp} ~\theta\right) 
= \frac{-\eta}{\alpha_{Exp}} \left\{ -\alpha_{Exp} ~\theta -(\alpha_{Exp} ~\theta)^2/2 - \cdots\right\} \\
& \approx \eta~ \theta + \frac{\alpha_{Exp}}{2}(\eta ~\theta^2 ) 
= H_{Var}(X). 
\end{array}
$$


### Properties of Premium Principles

Properties of premium principles help guide the selection of a premium principle in applications. [Table 9.2] provides examples of properties of premium principles.

[Table 9.2]:\#tab:9.2

<a id=tab:9.2></a>

Table 9.2. **Common Properties of Premium Principles**

$$
\small{
\begin{array}{ll}
\text{Description } & \text{Definition }\\\hline
\text{Nonnegative loading} & H(X) \ge {\rm E}[X] \\
\text{Additivity} & H(X_1+X_2) = H(X_1) + H(X_2), \text{ for independent }X_1, X_2  \\
\text{Scale invariance}  & H(cX) = c H(X), \text{ for }c \ge 0 \\
\text{Consistency} & H(c+X) = c + H(X)\\
\text{No rip-off }  & H(X) \le \max \{X\}\\
\hline
\end{array}
}
$$

This is simply a subset of the many properties quoted in the actuarial literature. For example, the review paper of @young2014premium lists 15 properties. See also the properties described as *coherent axioms* that we introduce for risk measures in Section \@ref(S:RiskMeasure).

Some of the properties listed in [Table 9.2] are mild in the sense that they will nearly always be satisfied. For example, the *no rip-off* property indicates that the premium charge will be smaller than the largest or "maximal" value of the loss $X$ (here, we use the notation $\max \{X\}$ for this maximal value which is defined as an "essential supremium" in mathematics). Other properties may not be so mild. For example, for a portfolio of independent risks, the actuary may want the *additivity* property to hold. It is easy to see that this property holds for the expected value, variance, and exponential premium principles but not for the standard deviation principle. Another example is the *consistency* property that does not hold for the expected value principle when the risk loading parameter $\alpha$ is positive.

The *scale invariance* principle is known as *homogeneity of degree one* in economics. For example, it allows us to work in different currencies (e.g., from dollars to Euros) as well as a host of other applications and will be discussed further in the following Section \@ref(S:HeterogeneousRisks). Although a generally accepted principle, we note that this principle does not hold for a large value of $X$ that may border on a surplus constraint of an insurer; if an insurer has a large probability of becoming insolvent, then that insurer may not wish to use linear pricing. It is easy to check that this principle holds for the expected value and standard deviation principles, although not for the variance and exponential principles.


## Reviewing Rate Adequacy {#S:PricingPrinciples}

After establishing the initial premiums, insurance company actuaries will perform rate reviews to measure the adequacy of those rates. For many regulated coverages (typically, personal lines insurance), actuaries file those rate reviews with the insurance regulator. Actuaries review rates regularly as rate levels require update to kepp pace with inflationary pressures. At times, the required rate will be have a decreasing trend; for example with improvements in vehicle safety technology or workplace safety. Of course, the primary purpose of the rate is to test whether the experience of the rate program is consistent with loss and expense assumptions underlying the current rates. 

### The Loss Ratio Method

The "loss ratio method" is a common approach to assess rate adequacy. The `r Gloss('loss ratio')` is the ratio of the sum of losses to the premium.

$$
\small{
\text{Loss Ratio} = \frac{\text{Loss}}{\text{Premium}} .
}
$$

When determining premiums, it is a bit counter-intuitive to emphasize this ratio because the premium component is built into the denominator. As we will see, the loss ratio method develops rate **changes** rather than rates; we can use rate changes to update past experience to get a current rate. We calculate rate changes by comparing the loss ratio of the experience period to the target loss ratio. This adjustment factor is then applied to current rates to determine new indicated rates.

We first provide an overview of the approach to promote understanding. Let us return to equation \@ref(eq:dPremiumEquation). Noting that the "pure premium" is the provision for loss in the rates, we have the following:

$$
\begin{equation}
\small{
\text{Premium} = \dfrac{\text{Discounted Pure Premiums} + \text{Discounted Fixed Expenses} }{\text{Premium Delay} - \text{Variable Expense Rate} - \text{Profit}}\\

\text{Premium Delay - Variable Expense Rate - Profit} = \dfrac{\text{Discounted Pure Premiums}}{\text{Premium}} + \dfrac{\text{Discounted Fixed Expenses}}{\text{Premium}}\\

\text{Premium Delay - Variable Expense Rate - Profit} - \dfrac{\text{Discounted Fixed Expenses}}{\text{Premium}} = \dfrac{\text{Discounted Pure Premiums}}{\text{Premium}}\\

\text{Premium Delay - Variable Expense Rate - Profit} - \dfrac{\text{Discounted Fixed Expenses}}{\text{Premium}} = \text{Target Discounted Loss Ratio}\\

}
\end{equation}
$$
For simplification we will not repeat that the components of the rate change factor are discounted. In the loss ratio method, we compare the projected loss ratio to the target loss ratio. A projected loss ratio that exceeds the target loss ratio implies the need for a rate increase. A projected loss ratio that is less than the target loss ratio implies the need for a rate decrease. 

The experience loss ratio is not simply calculated as the ratio of loss and premium. Actuaries adjust ...


* As with the development of pure premiums described above, actuaries will typically review claims experience over a multi-year (typically three to seven years) period to smooths the year-to-year randomness. The years in the experience period are simillaryl weighted to balance responsiveness to more recent experience and the stability of a longer-term period. 

* The numerator of the loss ratio will be *ultimate losses.* We provides a discoussion of the estimation of ultimate losses in the section on loss reserving.

* We need to adjust the experience period losses to the cost level of the proposed rate program. We discussed this trend adjustment is \@ref(S:Trending). We apply the trend factor from the average accident period of the experience period to the avearge accident date of the proposed rate program. For example, if we are estimating rates that will underlie twelve month policies written in calendar year 2025, the average accident date of the prospective rate program will be 31 December 2025 (sometimes rounded to 1 January 2026). The first policy of the prospective period will be written on 1 January 2025 and expire on 31 December 2025. Assuming even distribution of claim events during the policy, average accident date (midpoint) of that policy will be 1 July 2025. Correspondingly, the last policy of the prospective period will be written on 31 December 2025 and expire on 31 December 2026 with an average accident date (midpoint) of that policy will be 1 July 2026. The midpoint of all policies written under the proposed rate program is therefore 31 December 2025.  To adjust experience for accident year 2022, we apply 3.5 years of trend. The average accident date of accident year 2022 is July 1, 2022 - so 3.5 year is the distance in time to the average accident date of the proposed rate program.

* We also need to adjust premiums for the effect of rate changes. There are two common approaches to this adjustment. 

The Parallelogram Method: Premium on-level factors use historical rate change calculations. For example if the company adopted a +10% rate change on 1 July 2022, then the denominator of 2022 earned premium would need be adjusted by +7.5%. Policies written prior to 1 July 2022 would need to be adjusted by +10%; for the premium earned after 1 July 2022; half would be earned on policies written under the old rate levels and require the 10% adjustment and half would be written on policies written under the higher rate levels and require no adjustment. The weighted average of these adjustments if +7.5%. 

NOTE TO BRIAN: Do you want me to expand on this parallelogram method or provide reference or do we have it elsewhere.

* Extension of Exposures: The extension of exposure method is a more detailed approach which involved the re-rating of all historical policies at current rates. It is more precise as the parallelogram method relies on rate changes that were calculated as the average rate change given the mix of business at that time. However, the mix of business may change and the rate change effect on the current mix may be different. The extension of exposures does not rely on those average rate changes and instead relies on on current rates.

* Premium Trend - Experience period premiums must also be adjusted for for premium trend, and the basis of premium must match the loss trend. For example, insureds may purchase higher limits of coverage to protect against higher inflation. These higher limits would be reflected in the internal claims experience and may underlie the data used to measure loss trend. If we are considering these changes in the loss trend, then we also need to consider the effect of higher limit purchases in premium trend.


**Example. Loss Ratio Indicated Change Factor.** Assume the following information:

- Projected ultimate loss and LAE ratio = 65%
- Projected fixed expense ratio = 6.5%
- Variable expense  = 25%
- Target UW profit = 10%

With these assumptions, with equation \@ref(eq:IndicatedChangeFactor), the indicated change factor can be calculated as
$$
\small{
ICF = \frac{\text{(Losses + Fixed)}/\text{Premium}}{ 1 - V - Q_{target}} = \frac{0.65 + 0.065}{1- 0.25 - 0.10} = 1.10 .
}
$$

This means that overall average rate level should be increased by 10%.

***











